### ISSUE TITLE
Some doubts

### ISSUE THREAD

**Issue by liuxin123456789** [timdrysdale/pyoam#1]
Hello professor, may you please share the relevant papers and reference materials of this code, I don't understand some of the results. thank you very much.

**Comment by timdrysdale** [comment]
Thanks for your interest. This code is not officially supported. However, I've used it to generate results for the following papers:
https://ieeexplore.ieee.org/abstract/document/7928218
https://digital-library.theiet.org/content/journals/10.1049/iet-map.2017.0293
There is no intention to provide a user guide or further information on this code at this time.

**Comment by liuxin123456789** [comment]
Thank you very much, your suggestions are of great help to me. Can I keep in touch with you in the future?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tim Drysdale"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月24日(星期三) 晚上11:08
收件人:&nbsp;"timdrysdale/pyoam"<pyoam@noreply.github.com&gt;;
抄送:&nbsp;"清爽的八达鸟"<786548399@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [timdrysdale/pyoam] Some doubts (#1)





 
Thanks for your interest. This code is not officially supported. However, I've used it to generate results for the following papers:
 https://ieeexplore.ieee.org/abstract/document/7928218
 https://digital-library.theiet.org/content/journals/10.1049/iet-map.2017.0293
 There is no intention to provide a user guide or further information on this code at this time.

**Comment by timdrysdale** [comment]
Of course, Good luck!
